server:
  port: 8088

---

spring:
  application:
    name: configtest-dev
  config:
    import: optional:configserver:http://localhost:9900

---

management:
  endpoints:
    web:
      exposure:
        include: refresh